import prisma from "../../../prisma/client";
import { v4 as uuidv4 } from "uuid";
export default async function handler(req, res) {
  const { method } = req;
  const { userId, total, status, products, couponId } = req.body;

  switch (method) {
    case "POST":
      try {
        let totalUnits = products.reduce(
          (acc, product) => acc + product.quantity,
          0
        );

        const order = await prisma.order.create({
          data: {
            total,
            status,
            userId,
            couponId: couponId, // Aquí usas el ID del cupón que se envió desde el frontend.
          },
        });

        const orderDetail = products.map((product) => {
          return {
            orderId: order.id,
            productId: product.productId,
            quantity: product.quantity,
            unitPrice: product.unitPrice,
            size: product.size,
          };
        });

        await prisma.orderDetail.createMany({
          data: orderDetail,
        });

        // Si el total de unidades es 50 o más, generamos un cupón del 5% para la próxima compra.
        if (totalUnits >= 50) {
          const couponCode = uuidv4();
          await prisma.coupon.create({
            data: {
              code: couponCode,
              discountPercent: 5,
              description: "5% discount for next purchase of 24+ units",
              useOnce: true,
              used: false,
              userId: userId, // Asociamos el cupón con el usuario
              minPurchaseUnits: 24,
              autoGenerated: true,
            },
          });
          // Enviar respuesta con el cupón para informar al usuario.
          res.status(200).json({ order, message: "Order created", couponCode });
          return;
        }
        res.status(200).json({ order, message: "Order created" });
      } catch (error) {
        res
          .status(500)
          .json({ message: "Error creating one order", error: error.message });
      }
      break;

    case "GET":
      try {
        const userId = Number(req.query.userId); // Obtener el userId de los query parameters

        // Si userId existe, filtrar los pedidos por ese userId, si no, obtener todos los pedidos
        const orders = await prisma.order.findMany({
          where: userId ? { userId } : undefined,
          include: {
            user: true, // <- Aquí estás incluyendo la relación user.
            orderDetails: {
              include: {
                products: true,
              },
            },
          },
        });
        res.status(200).json(orders);
      } catch (error) {
        res
          .status(500)
          .json({ message: "Error fetching orders", error: error.message });
      }
      break;
    case "DELETE":
      try {
        if (req.query.id) {
          // Eliminar orden específica por ID
          const orderId = Number(req.query.id);
          await prisma.orderDetail.deleteMany({
            where: { orderId: orderId },
          });
          await prisma.order.delete({
            where: { id: orderId },
          });
          res.status(200).json({
            message: `Order with id ${orderId} deleted successfully.`,
          });
        } else {
          // Eliminar todas las órdenes
          await prisma.orderDetail.deleteMany();
          await prisma.order.deleteMany();
          res.status(200).json({ message: "All orders deleted successfully." });
        }
      } catch (error) {
        res
          .status(500)
          .json({ message: "Error deleting orders", error: error.message });
      }
      break;
    case "PUT":
      console.log("Recibiendo solicitud PUT con data:", req.body);

      try {
        const { orderId, status } = req.body;

        const updatedOrder = await prisma.order.update({
          where: { id: orderId },
          data: { status },
        });

        res.status(200).json(updatedOrder);
      } catch (error) {
        res.status(500).json({
          message: "Error updating order status",
          error: error.message,
        });
      }
      break;
    default:
      res.setHeader("Allow", ["GET", "POST", "DELETE"]);
      res.status(405).end(`Method ${method} Not Allowed`);
  }
}
